# Generated by Django 5.2.17 on 2026-08-17 19:33

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, help_text='Alternative words people search for. One per entry, lowercase.', size=None)),
                ('description', models.TextField(blank=True, help_text='Used on the /trades/<slug> explainer page.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trade_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('instalments_allowed', models.BooleanField(default=False)),
                ('instalment_note', models.CharField(blank=True, max_length=200)),
                ('duration_weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_schedule', models.CharField(blank=True, help_text='For example: Mon-Thu, 8am to 2pm', max_length=200)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='providers.provider')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='catalog.trade')),
            ],
            options={
                'ordering': ['provider', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProgramme',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('instalments_allowed', models.BooleanField(default=False)),
                ('instalment_note', models.CharField(blank=True, max_length=200)),
                ('duration_weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_schedule', models.CharField(blank=True, help_text='For example: Mon-Thu, 8am to 2pm', max_length=200)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.provider')),
                ('trade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.trade')),
            ],
            options={
                'verbose_name': 'historical programme',
                'verbose_name_plural': 'historical programmes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True)),
                ('places_offered', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('places_remaining', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='catalog.programme')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'start_date'), name='unique_intake_per_programme_date')],
            },
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['trade', 'fee'], name='catalog_pro_trade_i_ea16c1_idx'),
        ),
    ]
