# Generated by Django 5.2.17 on 2026-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="intake",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("places_offered__isnull", True),
                    ("places_remaining__isnull", True),
                    ("places_remaining__lte", models.F("places_offered")),
                    _connector="OR",
                ),
                name="intake_remaining_lte_offered",
            ),
        ),
    ]
