# Generated by Django 5.2.17 on 2026-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_intake_intake_remaining_lte_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogramme',
            name='certificate_awarded',
            field=models.CharField(blank=True, help_text='What the trainee receives on completion. Left blank if nothing is awarded.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalprogramme',
            name='fee_includes_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprogramme',
            name='fee_includes_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprogramme',
            name='fee_includes_ppe',
            field=models.BooleanField(default=False, help_text='Goggles, gloves, overalls and similar.'),
        ),
        migrations.AddField(
            model_name='historicalprogramme',
            name='fee_includes_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='certificate_awarded',
            field=models.CharField(blank=True, help_text='What the trainee receives on completion. Left blank if nothing is awarded.', max_length=200),
        ),
        migrations.AddField(
            model_name='programme',
            name='fee_includes_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='fee_includes_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='fee_includes_ppe',
            field=models.BooleanField(default=False, help_text='Goggles, gloves, overalls and similar.'),
        ),
        migrations.AddField(
            model_name='programme',
            name='fee_includes_tools',
            field=models.BooleanField(default=False),
        ),
    ]
