# Generated by Django 5.2.17 on 2026-08-17 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('free', 'Free listing'), ('standard', 'Standard'), ('featured', 'Featured')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending payment'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='providers.provider')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='subscription_period_ends_after_it_starts')],
            },
        ),
    ]
