# Generated by Django 5.2.17 on 2026-08-17 19:33

import django.db.models.deletion
import enquiries.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee_phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None)),
                ('trainee_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('reference_code', models.CharField(default=enquiries.models.generate_reference, editable=False, max_length=12, unique=True)),
                ('state', models.CharField(choices=[('pending_verification', 'Awaiting phone verification'), ('sent', 'Sent to provider'), ('failed', 'Delivery failed'), ('spam', 'Marked as spam')], default='pending_verification', max_length=25)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.intake')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.programme')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='providers.provider')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('visited', models.BooleanField(default=False)),
                ('enrolled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='enquiries.enquiry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee_phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None)),
                ('trainee_name', models.CharField(blank=True, max_length=120)),
                ('started_on', models.DateField()),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_on', models.DateField(blank=True, help_text='Did this person finish the programme, and when.', null=True)),
                ('provider_attestation', models.CharField(choices=[('not_asked', 'Not asked yet'), ('recommended', 'Would recommend for paid work'), ('not_recommended', 'Would not recommend')], default='not_asked', help_text='Would you recommend this graduate for paid work?', max_length=20)),
                ('attested_on', models.DateField(blank=True, null=True)),
                ('enquiry', models.OneToOneField(blank=True, help_text='Set only when this enrolment came through the platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolment', to='enquiries.enquiry')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='catalog.intake')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='catalog.programme')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='providers.provider')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['provider', '-created_at'], name='enquiries_e_provide_a7867f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['provider', '-started_on'], name='enquiries_e_provide_87919e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['completed_on', 'provider_attestation'], name='enquiries_e_complet_a8e893_idx'),
        ),
    ]
