# Generated by Django 5.2.17 on 2026-08-24 07:50

import uuid
from django.db import migrations, models


def populate_challenge_ids(apps, schema_editor):
    phone_verification = apps.get_model("enquiries", "PhoneVerification")
    for verification in phone_verification.objects.filter(challenge_id__isnull=True).iterator(
        chunk_size=500
    ):
        verification.challenge_id = uuid.uuid4()
        verification.save(update_fields=["challenge_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_phoneverification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phoneverification',
            name='enquiries_p_phone_13b6ca_idx',
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='challenge_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_challenge_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='phoneverification',
            name='challenge_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(choices=[('trainee_enquiry', 'Trainee enquiry'), ('trainer_access', 'Trainer access')], db_index=True, default='trainee_enquiry', max_length=30),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['phone', 'purpose', '-created_at'], name='enquiries_p_phone_4afa1d_idx'),
        ),
    ]
