# Generated by Django 5.2.17 on 2026-09-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enquiries",
            "0003_remove_phoneverification_enquiries_p_phone_13b6ca_idx_and_more",
        ),
        ("trainees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="trainee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to="trainees.traineeaccount",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="trainee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolments",
                to="trainees.traineeaccount",
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("trainee_enquiry", "Trainee enquiry"),
                    ("trainer_access", "Trainer access"),
                    ("trainee_access", "Trainee access"),
                ],
                db_index=True,
                default="trainee_enquiry",
                max_length=30,
            ),
        ),
    ]
