# Generated by Django 5.2.17 on 2026-09-16 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_trainee_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('trainee_access', 'Trainee access'), ('trainer_access', 'Trainer access'), ('staff_access', 'Back-office access'), ('add_to_account', 'Adding an address to an account')], db_index=True, default='trainee_access', max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='enquiries_e_email_d5c8e0_idx')],
            },
        ),
    ]
