# Generated by Django 5.2.17 on 2026-08-17 19:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import phonenumber_field.modelfields
import providers.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='The number a trainee is handed over to on WhatsApp.', max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geography.area')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical provider',
                'verbose_name_plural': 'historical providers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='The number a trainee is handed over to on WhatsApp.', max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='geography.area')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('phone', 'Phone call'), ('visit', 'Site visit')], default='whatsapp', max_length=20)),
                ('fees_confirmed', models.BooleanField(default=False)),
                ('intakes_confirmed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='providers.provider')),
            ],
            options={
                'ordering': ['-prompted_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVerification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('visited_on', models.DateField()),
                ('checks_performed', models.TextField(help_text='What was actually checked, in plain words. Shown to trainees verbatim.')),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('passed_with_notes', 'Passed with notes'), ('failed', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.provider')),
            ],
            options={
                'verbose_name': 'historical verification',
                'verbose_name_plural': 'historical verifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGovernmentStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not verified by Fliiptech')], default='not_claimed', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('accreditation_status', models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not verified by Fliiptech')], default='not_claimed', max_length=30)),
                ('documented_on', models.DateField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, help_text='Where this came from. Displayed exactly as documented, never inferred.', max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.provider')),
            ],
            options={
                'verbose_name': 'historical government status',
                'verbose_name_plural': 'historical government statuses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GovernmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not verified by Fliiptech')], default='not_claimed', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('accreditation_status', models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not verified by Fliiptech')], default='not_claimed', max_length=30)),
                ('documented_on', models.DateField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, help_text='Where this came from. Displayed exactly as documented, never inferred.', max_length=300)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_status', to='providers.provider')),
            ],
            options={
                'verbose_name_plural': 'government statuses',
            },
        ),
        migrations.CreateModel(
            name='ProviderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='providers/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('exif_stripped', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='providers.provider')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_reason', models.CharField(blank=True, max_length=200)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='providers.provider')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensions_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_on', models.DateField()),
                ('checks_performed', models.TextField(help_text='What was actually checked, in plain words. Shown to trainees verbatim.')),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('passed_with_notes', 'Passed with notes'), ('failed', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='providers.provider')),
            ],
            options={
                'ordering': ['-visited_on'],
                'get_latest_by': 'visited_on',
            },
        ),
        migrations.CreateModel(
            name='ProviderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('verification_evidence', 'Verification evidence'), ('id_document', 'Owner identification')], max_length=30)),
                ('file', models.FileField(storage=providers.models.private_storage, upload_to='evidence/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('exif_stripped', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='providers.provider')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='providers.verification')),
            ],
            options={
                'verbose_name_plural': 'provider evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='provider_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['status', 'area'], name='providers_p_status_7a2f61_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('area', 'slug'), name='unique_provider_slug_per_area'),
        ),
    ]
