# Generated by Django 5.2.17 on 2026-08-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'permissions': [('publish_provider', 'Can publish a provider listing')]},
        ),
    ]
