# Generated by Django 5.2.17 on 2026-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentstatus',
            name='accreditation_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not independently verified')], default='not_claimed', max_length=30),
        ),
        migrations.AlterField(
            model_name='governmentstatus',
            name='registration_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not independently verified')], default='not_claimed', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalgovernmentstatus',
            name='accreditation_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not independently verified')], default='not_claimed', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalgovernmentstatus',
            name='registration_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not registered'), ('not_claimed', 'Not claimed'), ('claimed_not_verified', 'Claimed, not independently verified')], default='not_claimed', max_length=30),
        ),
    ]
