# Generated by Django 5.2.17 on 2026-08-24 07:49

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_governmentstatus_accreditation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovider',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprovider',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('changes_requested', 'Changes requested'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('changes_requested', 'Changes requested'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('phone_verified_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='ProviderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='owner', max_length=20)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_memberships', to='providers.provider')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='providers.traineraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trainer',), name='one_provider_membership_per_trainer'), models.UniqueConstraint(fields=('provider',), name='one_trainer_membership_per_provider')],
            },
        ),
    ]
