# Generated by Django 5.2.17 on 2026-09-15 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def confirm_trainers_already_live(apps, schema_editor):
    """Owners whose listing is already public were effectively vetted.

    Everyone else starts as waiting for confirmation, which is the point of
    the change: a sign-up is not trusted until the super admin confirms it.
    """
    TrainerAccount = apps.get_model("providers", "TrainerAccount")
    TrainerAccount.objects.filter(
        memberships__provider__status="published",
    ).update(approval_status="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_historicalprovider_review_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="traineraccount",
            options={
                "ordering": ["phone"],
                "permissions": [
                    ("confirm_trainer", "Can confirm or decline trainer sign-ups")
                ],
            },
        ),
        migrations.AddField(
            model_name="traineraccount",
            name="approval_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="traineraccount",
            name="approval_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="traineraccount",
            name="approval_note",
            field=models.CharField(
                blank=True,
                help_text="Shown to the trainer when a sign-up is declined.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="traineraccount",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for confirmation"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(confirm_trainers_already_live, migrations.RunPython.noop),
    ]
