# Generated by Django 5.2.17 on 2026-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_trainer_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovider',
            name='declared_accurate_at',
            field=models.DateTimeField(blank=True, help_text='When the trainer last attested that fees and dates are current.', null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='landmark',
            field=models.CharField(blank=True, help_text='The nearest well-known place. For example: behind Tema Community 1 market.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='premises_tenure',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('shared', 'Shared or family premises')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='site_visit_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='trainee_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Trainees enrolled when the listing was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='trainer_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='People who teach at this workshop, including the owner.', null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='declared_accurate_at',
            field=models.DateTimeField(blank=True, help_text='When the trainer last attested that fees and dates are current.', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='landmark',
            field=models.CharField(blank=True, help_text='The nearest well-known place. For example: behind Tema Community 1 market.', max_length=200),
        ),
        migrations.AddField(
            model_name='provider',
            name='premises_tenure',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('shared', 'Shared or family premises')], max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='site_visit_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='trainee_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Trainees enrolled when the listing was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='trainer_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='People who teach at this workshop, including the owner.', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='data_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('ghana_card', 'Ghana Card'), ('passport', 'Passport'), ('voter_id', 'Voter ID')], max_length=20),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('lead_trainer', 'Lead trainer')], max_length=20),
        ),
    ]
