# Generated by Django 5.2.17 on 2026-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_historicalprovider_declared_accurate_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='traineraccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
