# Generated by Django 5.2.17 on 2026-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_traineraccount_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovider',
            name='logo',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='providerphoto',
            name='kind',
            field=models.CharField(choices=[('workshop', 'The workshop'), ('work', 'Work they have done')], db_index=True, default='workshop', max_length=20),
        ),
    ]
