# Generated by Django 5.2.17 on 2026-09-15 11:21

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import simple_history.models
import trainees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0004_historicalprovider_review_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTraineeAccount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True, max_length=128, region=None
                    ),
                ),
                ("phone_verified_at", models.DateTimeField()),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Typed by the trainee. Optional.",
                        max_length=120,
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("telegram", "Telegram")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop this number signing in. History is kept.",
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trainee",
                "verbose_name_plural": "historical trainees",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SupportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Granted only when the staff member holds the support edit permission.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=trainees.models.default_support_expiry
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ended_by_staff", "Ended by staff"),
                            ("expired", "Expired"),
                            ("replaced", "Replaced by a new session"),
                            ("staff_signed_out", "Staff signed out"),
                            ("account_disabled", "Trainee account disabled"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportSessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trainees.supportsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TraineeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("phone_verified_at", models.DateTimeField()),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Typed by the trainee. Optional.",
                        max_length=120,
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("telegram", "Telegram")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop this number signing in. History is kept.",
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "trainee",
                "verbose_name_plural": "trainees",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "support_access",
                        "Can open a trainee dashboard to help them (view only)",
                    ),
                    ("support_edit", "Can make changes while helping a trainee"),
                    ("erase_trainee", "Can erase a trainee's personal data on request"),
                ],
            },
        ),
        migrations.AddField(
            model_name="supportsession",
            name="trainee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_sessions",
                to="trainees.traineeaccount",
            ),
        ),
        migrations.CreateModel(
            name="SavedProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="providers.provider",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_providers",
                        to="trainees.traineeaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="supportsession",
            index=models.Index(
                fields=["staff_user", "-started_at"],
                name="trainees_su_staff_u_1dfff1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedprovider",
            constraint=models.UniqueConstraint(
                fields=("trainee", "provider"), name="one_save_per_trainee_provider"
            ),
        ),
    ]
