# Generated by Django 5.2.17 on 2026-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='education_level',
            field=models.CharField(blank=True, choices=[('not_in_school', 'Not in school'), ('jhs', 'JHS'), ('shs_general', 'SHS — general'), ('shs_technical', 'SHS — technical or vocational'), ('tvet', 'CTVET or other TVET institution'), ('university', 'University or other tertiary'), ('other', 'Something else')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='education_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'Still studying'), ('completed', 'Completed'), ('left', 'Left before finishing')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='education_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year completed, or the year they expect to finish.', null=True),
        ),
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='What they studied there. For example: building construction.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='institution_name',
            field=models.CharField(blank=True, help_text='The school, college or university. Typed by the trainee.', max_length=200),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='education_level',
            field=models.CharField(blank=True, choices=[('not_in_school', 'Not in school'), ('jhs', 'JHS'), ('shs_general', 'SHS — general'), ('shs_technical', 'SHS — technical or vocational'), ('tvet', 'CTVET or other TVET institution'), ('university', 'University or other tertiary'), ('other', 'Something else')], max_length=20),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='education_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'Still studying'), ('completed', 'Completed'), ('left', 'Left before finishing')], max_length=20),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='education_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year completed, or the year they expect to finish.', null=True),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='What they studied there. For example: building construction.', max_length=200),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='institution_name',
            field=models.CharField(blank=True, help_text='The school, college or university. Typed by the trainee.', max_length=200),
        ),
    ]
