# Generated by Django 5.2.17 on 2026-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_historicaltraineeaccount_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaltraineeaccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='traineeaccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
